// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {broadcast} from '../models';

export function GetBroadcastService():Promise<broadcast.Service>;

export function Greet(arg1:string):Promise<string>;

export function IsConnected():Promise<boolean>;
