// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBroadcastService() {
  return window['go']['main']['App']['GetBroadcastService']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}
